-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dimdate
(
    dateid integer NOT NULL,
    date date,
    year character varying(10) COLLATE pg_catalog."default",
    quarter character varying(10) COLLATE pg_catalog."default",
    quartername character varying(30) COLLATE pg_catalog."default",
    month character varying(20) COLLATE pg_catalog."default",
    monthname character varying(30) COLLATE pg_catalog."default",
    day character varying(20) COLLATE pg_catalog."default",
    weekday character varying(20) COLLATE pg_catalog."default",
    weekdayname character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT dimdate_pkey PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public.dimstation
(
    stationid integer NOT NULL,
    city character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT dimstation_pkey PRIMARY KEY (stationid)
);

CREATE TABLE IF NOT EXISTS public.dimtruck
(
    truckid integer NOT NULL,
    trucktype character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT dimtruck_pkey PRIMARY KEY (truckid)
);

CREATE TABLE IF NOT EXISTS public.facttrips
(
    tripid integer NOT NULL,
    dateid integer,
    stationid integer,
    truckid integer,
    wastecollected double precision,
    CONSTRAINT facttrips_pkey PRIMARY KEY (tripid)
);

CREATE TABLE IF NOT EXISTS public.mydimdate
(
    dateid integer NOT NULL,
    date date,
    year character varying(10) COLLATE pg_catalog."default",
    quarter character varying(10) COLLATE pg_catalog."default",
    quatername character varying(10) COLLATE pg_catalog."default",
    month character varying(10) COLLATE pg_catalog."default",
    monthname character varying(20) COLLATE pg_catalog."default",
    day character varying(10) COLLATE pg_catalog."default",
    weekday character varying(5) COLLATE pg_catalog."default",
    weekdayname character varying(20) COLLATE pg_catalog."default",
    CONSTRAINT mydimdate_pkey PRIMARY KEY (dateid)
);

CREATE TABLE IF NOT EXISTS public.mydimwaste
(
    wasteid integer NOT NULL,
    wastetype character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT mydimwaste_pkey PRIMARY KEY (wasteid)
);

CREATE TABLE IF NOT EXISTS public.mydimzone
(
    zoneid integer NOT NULL,
    collectionzone character varying(20) COLLATE pg_catalog."default",
    city character varying(30) COLLATE pg_catalog."default",
    CONSTRAINT mydimzone_pkey PRIMARY KEY (zoneid)
);

ALTER TABLE IF EXISTS public.facttrips
    ADD CONSTRAINT facttrips_dateid_fkey FOREIGN KEY (dateid)
    REFERENCES public.dimdate (dateid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facttrips
    ADD CONSTRAINT facttrips_stationid_fkey FOREIGN KEY (stationid)
    REFERENCES public.dimstation (stationid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.facttrips
    ADD CONSTRAINT facttrips_truckid_fkey FOREIGN KEY (truckid)
    REFERENCES public.dimtruck (truckid) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;